defaults:
  - _self_
  - preset:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"
project_name: "OCRProject"
wandb: True
exp_version: "v1.0"
resume: null

trainer:
  max_epochs: 100
  num_sanity_val_steps: 0  # sanity check 비활성화 (on_validation_epoch_end 오작동 방지)
  log_every_n_steps: 100
  check_val_every_n_epoch: 1
  deterministic: True
